version: "3.7"

services:
    web:
        image: nginx
        restart: always
        hostname: nginx_gw
        container_name: nginx_gw
        working_dir: /app
        volumes:
            - ../gw:/app
            - ./httpd:/etc/nginx/conf.d/
        ports:
            - "4000:80"
        networks:
            - webnet
        depends_on:
            - backend

    backend:
        build:
            context: ./
            dockerfile: Dockerfile
        image: gw
        container_name: gw
        hostname: gw
        volumes:
            - ../gw:/app
        networks:
            - webnet
        depends_on:
            - db
    
    db:
        image: mysql:8.0.30
        command: --default-authentication-plugin=mysql_native_password
        hostname: db
        container_name: db
        restart: always
        volumes:
            - gw:/var/lib/mysql
        networks:
            - webnet
        environment:
            MYSQL_ROOT_PASSWORD: var0kah
            # MYSQL_DATABASE: app_db
            # MYSQL_USER: db_user
            # MYSQL_PASSWORD: secret

    
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     container_name: pma
    #     links:
    #         - db
    #     environment:
    #         PMA_HOST: db
    #         PMA_PORT: 3306
    #         PMA_ARBITRARY: 1
    #         restart: always
    #     ports:
    #         - '8081:80'
    #     networks:
    #         - webnet
        
    # adminer:
    #     image: adminer
    #     restart: always
    #     container_name: adminer
    #     hostname: adminer
    #     ports:
    #     - "8080:8080"
    #     networks:
    #     - webnet
    #     links:
    #     - db
    #     depends_on:
    #     - db 
        
networks:
  webnet:
    external:
      name: webnet

volumes:
 gw:
